services:
- docker
env:
  global:
  - TERM=dumb
  - DOCKER_USERNAME=daggerok
  - DOCKER_IMAGE_NAME=glassfish
  - secure: knCu9Q6hsdN+dQji73AejB3zdu8ms/z+8OKkWSTg1FNnwnMmMFfM2+nXTmU2Bsp+G279COUdT9onMILlrN8yrb+IulHtN4whulN9Ag52mLGkNTMZz8lZ8/Y9jcXC+KAebPRd923mIuAnQ4oTmmGTCBl7imUKFrOzDekCcTmsUvWeXxYSUgsnB4c7gvK1hE0V9OBvwjcIbDzRHFkHLPT+DHdNad3G+VUc/G8+UTXBtxay3vWW66Z7x7xcl+XTCS74+kOjw+7GXN2ZRWQA9ek4rPpVHS5r4EY4o+OC8j34DFytp6MDwgjV40xTtT750/yuz4W0TEnKv6UVjjTdsBfawNIElCUQiYk6xd58Qi36tAVEh7t+HHujIsgF51Gl6oVIIKuMHl4vHE/YLZ7WIxSxDWw6VSLzzoyidsL57vx/IIq/dNQsYH6m2iTnKFGTs4QusLEjVFwzwS1rKHpCQuBhfV3e8YHB3U/fFqM37Ya29n0yoAFUEcxS8CcMLMlnfAmU/xFEifLvBKDPHXb+7+LFt2FG4nqt8sbsyxP1FfSapVqPSqTtqtl49wQCm8b5aZVXX5Kc8G9cN/Ipdh+Fu5VoarRqnKPkKDxyfqUlbu8i5yU1NK25BZgBDjyTPgheu1HY7Ngmo3L8q7LhRXr2oZTJ6R1C1f7e98tB95PQER+bdEk=
script:
- docker build -t ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} .
- |
  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest
    docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest-alpine
  else
    docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BRANCH}
    docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BRANCH}-alpine
  fi
- docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
- docker push ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}
