services:
- docker
env:
  global:
  - TERM=dumb
  - DOCKER_USERNAME=daggerok
  - DOCKER_IMAGE_NAME=glassfish
  - secure: EEEA8Ut61xCAv1wDRXSY9I1FKLhRYGUvXIqYqX3YD1sGM+mKxDZCc6WXio20QdXBKU0zBAEbh1VbB+lQDjXNrFT4DV54QbuJCkz01sbvYHEfT9O0VjPXxShZdW2ngdpQP00Ghbpcs0SX28duoRdzjDIc+wFK6DH7zIfsqCnl3isrKazd9cinhnRvmU2tIhZIRk8jX3XYm2+It71vnyRl7xiDbymy+mitoErPV8PXRamzaBFrRbkB+NZ6O+J7H5S/F78XQ+ThV7BA/HxUCJ2lTzfY2x7MBNunqlVJL+3MdJrXg61r1TXiBvjsQ0IUnTV3mzt1RlQYnoE8BPbkWsdhulGxGJGmjBt/BStwvGTcaagSHW0afb4cZeAKV74jZbNdnv6/TuQPNLFBNM54pp9muJe5NzI5DadSKU+hIbNe84D0Qj0J5kPF2rHpCcb8Cy90nSpjslj4altBXuuKET3P1r3alyMCS9pwzbIy/FYhLDGlknJ3zgs4ADigLiZznTSvnyABzCn64aipccegCN8U7vEYzCxhSwWzuQZtxdS325n5CgvHy/p8WyKYBFpSiLjbyrm4f/WGqZHvJU6Xz9wGch3Vh/nI6yAEHpns8wGujYhFhLo0eLr2ELgHtRq49krQewj/F7t2YF2WySPDU1EpoCj3XVE/4zfeATksoRw0khY=
  - secure: IWGaAPmfWQXRMYryLAwJ4VcyuaiOcVkciz7W+EnOl8nuPPJSmsjbCJnB4pXAy1CF1jvkwr84S0i8vqtCYwLw4tK+Hw2BLs+v3hVb3eEjU/7rHwbAoZUKKQonXP29cdErth3vIsGla+VEwAcoswU0EHxwRdruXR5jM3SjHBRnHmbc6HD83aBiawyCzMEZi8tru5+YQJn1qQffAGZ/woIaplpsSBdaoH9sGCsa8+HHes3YglUxy9QFthwVOZnm4Uvq2LJFMwCCiguiP43lPVwWVQFxYzhmvjZo5h30DUXu9/F+656MgxvIIXAsmIeK6SniEAEPttEnzVbDXkUQog5psmJhHlKL3aNrhvdY11njYLuLH2l9qlK1q5IuOoUqUix4LooQteMFpWG6vrX5yYPPABoGwqLQKdjVFFPmgy3fwwWBbLuxyLGI5m/tojFacN24WS7w8mQocTRZ240cnkZMIl23qxMn7q09824E3x1SF96dojqFn7nsR3UtjZVvxBMOw6lkFJVAFzH3s64ICYfHwk0X/7RBunwAEYndFVZyWl/oKVw8+qapm2QAVBvlLFbgC+Y5vaJJB/HI6Q/xf+cjrpE1f0gABAT0Ez7cqrg9bxW68Icw7LmevQH7PmCh4uc27Qyrszoplxa+oWeD25vqdb0MlkjoSW46a1WKWpuURro=
script:
- docker build -t ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} .
- |
  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest
    docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest-alpine
  else
    docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BRANCH}
    docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BRANCH}-alpine
  fi
- docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
- docker push ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}
